#!/usr/bin/env python3
"""Generate synthetic training data for task classification."""

import json
import random

# Task categories and example prompts
TASK_DATA = {
    "coding": [
        "How do I fix this bug in my code?",
        "Write a function that sorts a list",
        "Debug this error: TypeError in Python",
        "Refactor this class to use composition",
        "How do I implement a binary search tree?",
        "Fix the memory leak in this C++ code",
        "Write unit tests for this module",
        "Optimize this SQL query for performance",
        "How do I use async/await in JavaScript?",
        "Implement a REST API endpoint",
        "Why is my code throwing a null pointer exception?",
        "Convert this loop to a list comprehension",
        "Add error handling to this function",
        "Write a regex to validate email addresses",
        "How do I connect to PostgreSQL in Python?",
        "Implement OAuth2 authentication",
        "Fix the CORS error in my frontend",
        "Write a recursive function for factorial",
        "How do I deploy to Kubernetes?",
        "Optimize this React component rendering",
        "Create a Dockerfile for this app",
        "How do I use generics in TypeScript?",
        "Implement caching in this API",
        "Write a custom hook in React",
        "How do I handle exceptions in async code?",
    ],
    "cooking": [
        "How do I bake a chocolate cake?",
        "What's the recipe for pasta carbonara?",
        "How long should I cook a steak?",
        "What temperature to roast chicken?",
        "How do I make homemade pizza dough?",
        "Recipe for vegetable stir fry",
        "How to caramelize onions properly?",
        "What's the best way to cook salmon?",
        "How do I make fluffy scrambled eggs?",
        "Recipe for chocolate chip cookies",
        "How do I cook rice perfectly?",
        "What spices go well with chicken?",
        "How to make a roux for gravy?",
        "Recipe for homemade bread",
        "How do I grill vegetables?",
        "What's the secret to crispy bacon?",
        "How to make a vinaigrette dressing?",
        "Recipe for chicken soup",
        "How do I bake without eggs?",
        "What temperature for medium rare steak?",
        "How to make mashed potatoes creamy?",
        "Recipe for banana bread",
        "How do I cook quinoa?",
        "What's the ratio for pie crust?",
        "How to make caramel from scratch?",
    ],
    "research": [
        "Research the latest developments in quantum computing",
        "Find information about climate change effects",
        "Compare different machine learning frameworks",
        "What are the current trends in AI?",
        "Research the history of ancient Rome",
        "Find studies on sleep and productivity",
        "Compare electric vs gas cars",
        "What's the state of blockchain technology?",
        "Research cryptocurrency regulations",
        "Find information about renewable energy",
        "Compare different diet approaches",
        "What does research say about meditation?",
        "Research the benefits of exercise",
        "Find information about space exploration",
        "Compare programming languages for web dev",
        "What are the latest medical breakthroughs?",
        "Research economic indicators",
        "Find studies on remote work productivity",
        "Compare cloud providers",
        "What's the history of the internet?",
        "Research sustainable farming practices",
        "Find information about mental health",
        "Compare different investment strategies",
        "What does science say about fasting?",
        "Research the future of transportation",
    ],
    "math_reasoning": [
        "What is 15% of 200?",
        "Calculate the compound interest",
        "Solve for x: 2x + 5 = 15",
        "What's the derivative of x^2?",
        "Calculate the area of a circle",
        "What is the Pythagorean theorem?",
        "Solve this integral",
        "Calculate the standard deviation",
        "What's the probability of rolling a 6?",
        "Find the roots of this quadratic",
        "Calculate the volume of a sphere",
        "What is log base 10 of 100?",
        "Solve the system of equations",
        "Calculate the mean and median",
        "What's the formula for slope?",
        "Find the limit as x approaches infinity",
        "Calculate the dot product",
        "What is the Fibonacci sequence?",
        "Solve for the hypotenuse",
        "Calculate the perimeter",
        "What's the binomial coefficient?",
        "Find the derivative of sin(x)",
        "Calculate the eigenvalues",
        "What is the gamma function?",
        "Solve this differential equation",
        "Prove that sqrt(2) is irrational",
        "What's the chain rule in calculus?",
        "Explain Bayes' theorem",
        "Derive the quadratic formula",
        "What is the central limit theorem?",
    ],
    "creative": [
        "Write a story about time travel",
        "Create a poem about the ocean",
        "Write a screenplay for a short film",
        "Generate a creative business name",
        "Write a song about love",
        "Create a fictional character biography",
        "Write a dialogue between two strangers",
        "Generate ideas for a novel",
        "Write a humorous essay",
        "Create a fantasy world description",
        "Write a persuasive speech",
        "Generate a plot twist for a mystery",
        "Write a children's story",
        "Create a sci-fi scenario",
        "Write a monologue",
        "Generate creative metaphors",
        "Write a review in a unique style",
        "Create a backstory for a villain",
        "Write a letter from the future",
        "Generate a tagline for a product",
        "Write a horror story opening",
        "Create a world-building element",
        "Write in the style of Shakespeare",
        "Generate a creative ending",
        "Write a dream sequence",
    ],
    "qa": [
        "What is the capital of France?",
        "Who wrote Romeo and Juliet?",
        "When was the Declaration of Independence signed?",
        "What is photosynthesis?",
        "Who invented the telephone?",
        "What's the largest planet in our solar system?",
        "When did World War II end?",
        "What is the speed of light?",
        "Who painted the Mona Lisa?",
        "What's the chemical formula for water?",
        "When was the internet invented?",
        "What is the population of Japan?",
        "Who discovered penicillin?",
        "What's the tallest mountain?",
        "When did humans first walk on the moon?",
        "What is the theory of relativity?",
        "Who wrote 1984?",
        "What's the boiling point of water?",
        "When was the first computer built?",
        "What is the distance to the sun?",
        "Who was the first US president?",
        "What's the currency of the UK?",
        "When did the Roman Empire fall?",
        "What is the human genome?",
        "Who developed the theory of evolution?",
    ],
    "general": [
        "Hello, how are you?",
        "Tell me a joke",
        "What's the weather like?",
        "How's your day going?",
        "Can you help me with something?",
        "I'm bored, entertain me",
        "What's new?",
        "Good morning!",
        "Thanks for your help",
        "That's interesting",
        "I agree with you",
        "Can you explain that again?",
        "I don't understand",
        "That makes sense",
        "Goodbye for now",
        "See you later",
        "Take care",
        "Have a nice day",
        "Nice to meet you",
        "What do you think?",
        "Any suggestions?",
        "I'm not sure about that",
        "Could be better",
        "Sounds good to me",
        "Let me think about it",
    ],
    "vision": [
        "What's in this image?",
        "Describe this photo",
        "Can you read the text in this screenshot?",
        "What color is the car in this picture?",
        "How many people are in this image?",
        "Is there a dog in this photo?",
        "Describe the scene in this image",
        "What object is highlighted in this picture?",
        "Can you identify this plant from the photo?",
        "What does this chart show?",
        "Read the license plate in this image",
        "What's written on this sign?",
        "Describe the architecture in this photo",
        "What type of animal is in this picture?",
        "Can you transcribe this handwritten note?",
        "What emotion is the person showing?",
        "Is this image AI generated?",
        "Describe the layout of this room",
        "What's the weather in this photo?",
        "Identify the objects on this table",
        "Can you see any text in this image?",
        "What style of art is this?",
        "Describe the fashion in this photo",
        "What's happening in this meme?",
        "Analyze this screenshot for errors",
    ],
    "embedding": [
        "Find documents similar to this text",
        "Search for related articles",
        "What's semantically similar to this?",
        "Find duplicate content",
        "Cluster these texts by topic",
        "What's the similarity between these documents?",
        "Recommend similar products",
        "Find matching records in the database",
        "Semantic search for this query",
        "Compare these two texts for similarity",
        "Group these items by meaning",
        "Find near-duplicates in this dataset",
        "What documents are related to this topic?",
        "Rank these by relevance",
        "Build a similarity index",
        "Find the closest match",
        "Search embeddings for this query",
        "What's the cosine similarity?",
        "Create vector representations",
        "Index this for semantic search",
    ],
    "tools": [
        "Call the weather API",
        "Search the web for this",
        "Execute this function",
        "Use the calculator tool",
        "Send an email",
        "Create a calendar event",
        "Query the database",
        "Run this shell command",
        "Make an HTTP request",
        "Invoke this API endpoint",
        "Use the file system tool",
        "Call the translation service",
        "Execute this SQL query",
        "Post to the webhook",
        "Use the browser tool",
        "Connect to the database",
        "Run this Python code",
        "Make a REST API call",
        "Use the search tool",
        "Call this function with these parameters",
    ],
    "translation": [
        "Translate this to Spanish",
        "What's this in French?",
        "Convert to Japanese",
        "Translate from German to English",
        "How do you say hello in Chinese?",
        "Translate this paragraph",
        "Convert this text to Portuguese",
        "What's the Italian word for love?",
        "Translate this document",
        "Change to Russian",
        "Translate to Arabic",
        "What's this in Korean?",
        "Convert to Hindi",
        "Translate this sentence",
        "How do you say goodbye in German?",
        "Translate this email",
        "Convert from Spanish",
        "What's the French equivalent?",
        "Translate to Dutch",
        "Convert this to Swedish",
    ],
    "summarization": [
        "Summarize this article",
        "Give me the key points",
        "What's the TL;DR?",
        "Condense this text",
        "Summarize the main ideas",
        "Give me a brief overview",
        "What are the highlights?",
        "Shorten this document",
        "Summarize this meeting notes",
        "Create an abstract",
        "What's the gist?",
        "Summarize this chapter",
        "Give me the executive summary",
        "Condense this report",
        "What's this about in one sentence?",
        "Summarize this paper",
        "Key takeaways from this text",
        "Summarize this conversation",
        "Create a summary",
        "What's the main point?",
    ],
}


def generate_dataset(samples_per_class=200, output_file="tasks.jsonl"):
    """Generate a balanced dataset with variations."""
    
    dataset = []
    
    for task, prompts in TASK_DATA.items():
        for _ in range(samples_per_class):
            # Pick a random base prompt
            base = random.choice(prompts)
            
            # Add variations
            variations = [
                base,
                base.lower(),
                base.upper()[:1] + base[1:].lower(),  # Capitalize first
                f"Please {base.lower()}",
                f"Can you {base.lower()}?",
                f"I need you to {base.lower()}",
                f"Help me: {base}",
                f"{base} Thanks!",
            ]
            
            prompt = random.choice(variations)
            
            # Sometimes add noise
            if random.random() < 0.2:
                typos = {"a": "@", "e": "3", "i": "1", "o": "0"}
                for k, v in typos.items():
                    if random.random() < 0.3:
                        prompt = prompt.replace(k, v, 1)
            
            dataset.append({
                "text": prompt,
                "label": task
            })
    
    # Shuffle
    random.shuffle(dataset)
    
    # Write to file
    with open(output_file, "w") as f:
        for item in dataset:
            f.write(json.dumps(item) + "\n")
    
    print(f"Generated {len(dataset)} samples")
    print(f"Labels: {set(item['label'] for item in dataset)}")
    print(f"Saved to {output_file}")
    
    # Show distribution
    from collections import Counter
    label_counts = Counter(item["label"] for item in dataset)
    print("\nDistribution:")
    for label, count in sorted(label_counts.items()):
        print(f"  {label}: {count}")


if __name__ == "__main__":
    generate_dataset(samples_per_class=200)
